# Generated by Django 6.1.1 on 2026-10-05 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('comentarios', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('SIMPLE', 'Simple'), ('LIBRE', 'Libre')], max_length=6)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('requerida', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_evaluado', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'Proceso'), ('TERMINADA', 'Terminada')], default='PENDIENTE', max_length=10)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_final', models.DateTimeField(blank=True, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.cuestionario')),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('valor', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.pregunta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='evaluaciones.cuestionario')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.seccion'),
        ),
        migrations.CreateModel(
            name='RespuestaLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_libres', to='evaluaciones.evaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta')),
            ],
            options={
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_simples', to='evaluaciones.evaluacion')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta')),
            ],
            options={
                'unique_together': {('evaluacion', 'pregunta')},
            },
        ),
    ]
